### ISSUE TITLE
Remove hard coded strings

### ISSUE THREAD

**Issue by Korkmatik** [StepUp-eHealth-Application/StepUp-Frontend#11]
Use string resources instead, so it will be easier to translate the app into other languages

**Comment by myselfdeepdas** [comment]
How can i work on this project and i want to contribute on it , and i am a new bie in android development.

**Comment by Korkmatik** [comment]
Hi @myselfdeepdas,

thanks for your interest. Really appreciate it! 

This issue was created because most of the strings for the UI are hard coded. We should use string ressources instead. The task is: Moving these strings into [string ressources](https://developer.android.com/guide/topics/resources/string-resource). 

If you want to contribute, just fork the repository and work on the issue. After finishing the task, please create a merge request here.

You will need a (virtual) device with Android API 28 or higher. You can find a step by step guide on setting up your environment [in the wiki](https://github.com/StepUp-eHealth-Application/StepUp-Frontend/wiki/Frontend). Unfortunatly the wiki is only available in German right now. We will be translating it to English later. But there are also some screenshots which will help you. 

Feel free to ask if you have any more questions :)

Thanks and regards!

**Comment by sdarshil6** [comment]
Hi. So I forked the project to solve the issue of hardcoded strings. I copied the ids of textviews, buttons and named is as string-name in resources. But the problem I am facing is that I encountered textviews with SAME id but DIFFERENT texts. So can you advise me what I should do about that? Should I change the ids of these textviews by myself?

![github problem](https://user-images.githubusercontent.com/85783343/147757105-0ae24420-062e-49ba-b0e0-9fe26efdb6b8.png)

**Comment by Korkmatik** [comment]
Hi @sdarshil6,

thanks for contributing! You have to give them other names. That should fix it. Can you please show me the error you get?

**Comment by sdarshil6** [comment]
> Hi @sdarshil6,
> 
> thanks for contributing! You have to give them other names. That should fix it. Can you please show me the error you get?


Oh! I can give it other names. Thanks. I thought I had to ask you what names I should give. Good. I will do that. The error is that I can't gives two string resources the same names.

**Comment by sdarshil6** [comment]
> Hi @sdarshil6,
> 
> thanks for contributing! You have to give them other names. That should fix it. Can you please show me the error you get?



**THIS IS THE ERROR THAT I AM FACING :**

![error](https://user-images.githubusercontent.com/85783343/147913410-8dbcb95e-1753-4b8a-8f4a-4446149dfa00.png)
